core/accounts/urls.py
from django.urls import path, include
from .views import SignUpView, ProfileView
from django.views.generic import RedirectView
from .views import MyLoginView, swagger_logout_view
from django.contrib.auth.views import LogoutView

app_name = "accounts"

urlpatterns = [
    path("", RedirectView.as_view(url="blog/", query_string=True, permanent=False)),
    # path('',include('django.contrib.auth.urls')),
    path("login/", MyLoginView.as_view(), name="login"),
    path(
        "logout/",
        LogoutView.as_view(next_page="/accounts/login/"),
        name="logout",
        kwargs={"swagger_schema": None},
    ),
    path("signup/", SignUpView.as_view(), name="signup"),
    path("<int:pk>/profile/", ProfileView.as_view(), name="profile"),
    path("api/v1/", include("accounts.api.v1.urls")),
    # Swagger-only URL (appears in Swagger UI)
    path("swagger-logout/", swagger_logout_view, name="swagger-logout"),
]

core/blog/urls.py
from django.urls import path
from .views import BlogHomeView, BlogSingleView
from blog.feeds import LatestEntriesFeed

app_name = "blog"

urlpatterns = [
    path("", BlogHomeView.as_view(), name="blog_home"),
    path("category/<str:cat_name>/", BlogHomeView.as_view(), name="category"),
    path("author/<str:author>/", BlogHomeView.as_view(), name="author"),
    path("search/", BlogHomeView.as_view(), name="search"),
    path("tag/<str:tag_name>/", BlogHomeView.as_view(), name="tag"),
    path("<int:pid>", BlogSingleView.as_view(), name="blog_single"),
    path("rss/feed/", LatestEntriesFeed()),
]

core/comment/api/v1/urls.py
from django.urls import path, include
from rest_framework.routers import DefaultRouter
from .views import TaskModelViewSet, WeatherAPIView

app_name = "api-v1"

router = DefaultRouter()
router.register("task", TaskModelViewSet, basename="task")

urlpatterns = [
    path("<int:pid>/", include(router.urls)),
    path("weather/", WeatherAPIView.as_view(), name="weather"),
]

core/comment/urls.py
from django.urls import path, include
from .views import (
    TaskEditView,
    TaskDeleteView,
    TaskCompleteView,
    TaskView,
    test,
    weather,
    WeatherView,
)

app_name = "comment"

urlpatterns = [
    path("<int:pid>", TaskView.as_view(), name="task"),
    path("<int:pid>/<int:pk>/edit/", TaskEditView.as_view(), name="task-edit"),
    path("<int:pid>/<int:pk>/delete/", TaskDeleteView.as_view(), name="task-delete"),
    path(
        "<int:pid>/<int:pk>/complete/",
        TaskCompleteView.as_view(),
        name="task-complete",
    ),
    path("api/v1/", include("comment.api.v1.urls")),
    # Test Celery:
    path("test/", test, name="test"),
    # Test Redis for cache:
    path("weather/", weather, name="weather"),
    # Show graphical weather data:
    path("weather_show/", WeatherView.as_view(), name="weather_show"),
]

core/core/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from rest_framework import permissions
from drf_yasg.views import get_schema_view
from drf_yasg import openapi
from django.contrib.sitemaps.views import sitemap
from website.sitemaps import StaticViewSitemap
from blog.sitemaps import BlogSitemap
import debug_toolbar

sitemaps = {"static": StaticViewSitemap, "blog": BlogSitemap}


# for api document
schema_view = get_schema_view(
    openapi.Info(
        title="Blog API",
        default_version="v1",
        description="API documentation",
        terms_of_service="https://www.google.com/policies/terms/",
        contact=openapi.Contact(email="a_anvari@ymail.com"),
        license=openapi.License(name="BSD License"),
    ),
    public=True,
    permission_classes=(permissions.AllowAny,),
)

urlpatterns = [
    path("admin/", admin.site.urls),
    path("comment/", include("comment.urls")),
    path("accounts/", include("accounts.urls")),
    path("", include("accounts.urls")),
    path("api-auth/", include("rest_framework.urls")),
    path("website/", include("website.urls")),
    path("blog/", include("blog.urls")),
    path("post/", include("post.urls")),
    # your API endpoints here
    path(
        "swagger/",
        schema_view.with_ui("swagger", cache_timeout=0),
        name="schema-swagger-ui",
    ),
    path(
        "redoc/",
        schema_view.with_ui("redoc", cache_timeout=0),
        name="schema-redoc",
    ),
    path(
        "swagger.json",
        schema_view.without_ui(cache_timeout=0),
        name="schema-json",
    ),
    path(
        "sitemap.xml",
        sitemap,
        {"sitemaps": sitemaps},
        name="django.contrib.sitemaps.views.sitemap",
    ),
    path("robots.txt", include("robots.urls")),
    path("__debug__/", include(debug_toolbar.urls)),
    path("summernote/", include("django_summernote.urls")),
    path("captcha/", include("captcha.urls")),
    path("maintenance/", include("config.urls")),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

core/comment/models.py
from django.db import models
from django.urls import reverse


# Create Task model:
class Task(models.Model):
    author = models.ForeignKey(
        "accounts.Profile", on_delete=models.CASCADE, related_name="comment_tasks"
    )
    post = models.ForeignKey(
        "blog.Post", on_delete=models.CASCADE, related_name="comment_tasks"
    )
    title = models.CharField(max_length=250, default="test")
    status = models.BooleanField(default=False)
    created_date = models.DateTimeField(auto_now_add=True)
    updated_date = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.title

    def get_snippet(self):
        return self.title[0:2]

    # def get_absolute_api_url(self):
    #     return reverse("comment:api-v1:task-detail", kwargs={"pk": self.pk})

    def get_absolute_api_url(self):
        return reverse(
            "comment:api-v1:task-detail",
            kwargs={
                "pid": self.post_id,
                "pk": self.pk,
            },
        )

core/comment/forms.py
from django import forms
from .models import Task


class TaskForm(forms.ModelForm):

    class Meta:
        model = Task
        fields = ["author", "post", "title"]
        widgets = {
            "author": forms.HiddenInput(),
        }

core/comment/api/v1/views.py
from .serializers import TaskSerializer, WeatherSerializer
from ...models import Task
from blog.models import Post
from accounts.models import Profile
from rest_framework import viewsets, filters
from rest_framework.permissions import IsAuthenticated

from django_filters.rest_framework import DjangoFilterBackend
from .paginations import DefaultPagination
from rest_framework.views import APIView
import requests
from rest_framework.response import Response
from django.shortcuts import get_object_or_404
from django.core.cache import cache


class TaskModelViewSet(viewsets.ModelViewSet):
    permission_classes = [IsAuthenticated]
    # , IsOwnerOrReadOnly]
    serializer_class = TaskSerializer
    # queryset = Task.objects.all()

    filter_backends = [
        DjangoFilterBackend,
        filters.SearchFilter,
        filters.OrderingFilter,
    ]
    filterset_fields = ["author", "status"]
    search_fields = ["title"]
    ordering_fields = ["published_date"]

    pagination_class = DefaultPagination

    def get_queryset(self):
        pid = self.kwargs["pid"]
        user = self.request.user
        if not user or not user.is_authenticated:
            return Task.objects.none()  # Avoid 500
        return Task.objects.filter(author__user=user, post__id=pid)

    def perform_create(self, serializer):
        post_id = self.kwargs["pid"]
        post = get_object_or_404(Post, id=post_id)
        profile = Profile.objects.get(
            user=self.request.user
        )  # Fetch profile explicitly
        serializer.save(post=post, author=profile)


# Weather API:
# @method_decorator(cache_page(10,key_prefix='weather'), name='dispatch')
class WeatherAPIView(APIView):
    # permission_classes = [IsAuthenticated]
    serializer_class = WeatherSerializer

    def get(self, request):
        API_KEY = "6075f690e844e83ffc96d4ddf40c8b18"
        city = "Tehran"
        cache_key = "weather"
        cached_data = cache.get(cache_key)

        if cached_data is None:
            url = f"http://api.openweathermap.org/data/2.5/weather?q={city}&appid={API_KEY}&units=metric"
            response = requests.get(url)

            if response.status_code == 200:
                data = response.json()
                cache.set(cache_key, data, timeout=60 * 20)  # cache 20 minutes
                cached_data = data
            else:
                return Response(
                    {"error": "Failed to fetch weather data"},
                    status=response.status_code,
                )

        serializer = WeatherSerializer(cached_data)
        return Response(serializer.data)

core/comment/views.py
from django.views.generic import ListView, TemplateView
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from .models import Task
from blog.models import Post
from accounts.models import Profile
from django.contrib.auth.mixins import (
    LoginRequiredMixin,
    PermissionRequiredMixin,
)
from django.urls import reverse_lazy
from .forms import TaskForm
from django.contrib.auth.models import Permission
from django.contrib.contenttypes.models import ContentType
from django.core.exceptions import PermissionDenied
from django.http import Http404
import requests
from django.http import JsonResponse
from django.urls import reverse

# from django.core.cache import cache
from django.views.decorators.cache import cache_page
from comment.tasks import add
from django.http import HttpResponse


# customize LoginRequiredMixin for redirect to login page first
class MyLoginRequiredMixin(LoginRequiredMixin):
    def get_login_url(self):
        return reverse_lazy("accounts:login")


# Combined CreateView and ListView
class TaskView(MyLoginRequiredMixin, CreateView, ListView):
    model = Task
    template_name = "comment/comment.html"
    context_object_name = "tasks"
    paginate_by = 50
    form_class = TaskForm

    def get_success_url(self):
        return reverse("comment:task", kwargs={"pid": self.object.post.id})

    def get_queryset(self):
        pid = self.kwargs["pid"]
        return Task.objects.filter(post__id=pid).order_by("-created_date")

    # def get_queryset(self):
    #     pid = self.kwargs['pid']
    #     user = self.request.user
    #     return (
    #     Task.objects
    #     .filter(post__id=pid, author__user=user)
    #     .order_by('-created_date')
    #     )

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["post"] = Post.objects.get(id=self.kwargs["pid"])
        return context

    def get_initial(self, **kwargs):
        initial = super().get_initial()
        if self.request.user.is_authenticated:
            initial["author"] = Profile.objects.get(user=self.request.user)
        return initial

    def form_valid(self, form):
        self.object = form.save()
        user = self.request.user
        content_type = ContentType.objects.get_for_model(Task)
        view_permission = Permission.objects.get(
            codename="view_task", content_type=content_type
        )
        user.user_permissions.add(view_permission)
        return super().form_valid(form)


class TaskEditView(MyLoginRequiredMixin, PermissionRequiredMixin, UpdateView):
    model = Task
    fields = ["title"]
    permission_required = "comment.view_task"
    template_name = "comment/comment_form.html"

    def get_success_url(self):
        return reverse("comment:task", kwargs={"pid": self.object.post.id})

    def get_queryset(self):
        queryset = super().get_queryset()
        return queryset.filter(author=Profile.objects.get(user=self.request.user))

    def get_object(self, queryset=None):
        if queryset is None:
            queryset = self.get_queryset()
        try:
            obj = super().get_object(queryset)
        except Http404:
            # Instead of 404, raise 403 here
            raise PermissionDenied
        return obj


class TaskDeleteView(MyLoginRequiredMixin, PermissionRequiredMixin, DeleteView):
    model = Task
    permission_required = "comment.view_task"
    template_name = "comment/comment_confirm_delete.html"

    def get_success_url(self):
        return reverse("comment:task", kwargs={"pid": self.object.post.id})

    def get_queryset(self):
        queryset = super().get_queryset()
        return queryset.filter(author=Profile.objects.get(user=self.request.user))

    def get_object(self, queryset=None):
        if queryset is None:
            queryset = self.get_queryset()
        try:
            obj = super().get_object(queryset)
        except Http404:
            # Instead of 404, raise 403 here
            raise PermissionDenied
        return obj


class TaskCompleteView(MyLoginRequiredMixin, PermissionRequiredMixin, UpdateView):
    model = Task
    fields = ["status"]
    template_name = "comment/comment_complete.html"
    permission_required = "comment.view_task"

    def get_success_url(self):
        return reverse("comment:task", kwargs={"pid": self.object.post.id})

    def form_valid(self, form):
        instance = form.save(commit=False)
        if instance.status is False:
            instance.status = True
        else:
            instance.status = False
        instance.save()
        return super(TaskCompleteView, self).form_valid(form)

    def get_queryset(self):
        queryset = super().get_queryset()
        return queryset.filter(author=Profile.objects.get(user=self.request.user))

    def get_object(self, queryset=None):
        if queryset is None:
            queryset = self.get_queryset()
        try:
            obj = super().get_object(queryset)
        except Http404:
            # Instead of 404, raise 403 here
            raise PermissionDenied
        return obj


# Test Celery task:
def test(request):
    result = add.delay(3, 3)
    print(result.id)
    return HttpResponse("done")


@cache_page(30)
def weather(request):
    API_KEY = (
        "6075f690e844e83ffc96d4ddf40c8b18"  # Replace with your OpenWeather API key
    )
    city = "Tehran"
    url = f"http://api.openweathermap.org/data/2.5/weather?q={city}&appid={API_KEY}&units=metric"
    response = requests.get(url)
    return JsonResponse(response.json())


# Weather Show:
class WeatherView(TemplateView):
    template_name = "comment/weather.html"

core/templates/comment/comment.html
{%load static%}

<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
  <meta http-equiv="x-ua-compatible" content="ie=edge" />
  <title>comment</title>
  <!-- MDB icon -->
  <link rel="icon" href="{% static "comment/img/mdb-favicon.ico" %}" type="image/x-icon" />
  <!-- Font Awesome -->
  <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.15.2/css/all.css" />
  <!-- Google Fonts Roboto -->
  <link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Roboto:wght@300;400;500;700;900&display=swap" />
  <!-- MDB -->
  <link rel="stylesheet" href="{% static "comment/css/bootstrap-to-do-list.min.css" %}" />
</head>

<body>
  <!-- Start your project here-->
  <style>
    #list1 .form-control {
      border-color: transparent;
    }
    #list1 .form-control:focus {
      border-color: transparent;
      box-shadow: none;
    }
    #list1 .select-input.form-control[readonly]:not([disabled]) {
      background-color: #fbfbfb;
    }
  </style>
  <section class="vh-100">
    <div class="container py-5 h-100">
      <div class="row d-flex justify-content-center align-items-center h-100">
        <div class="col">
          <div class="card" id="list1" style="border-radius: .75rem; background-color: #eff1f2;">
            <div class="card-body py-4 px-4 px-md-5">
              
              <a href="#" onclick="document.getElementById('logout-form').submit();" class="primary-btn">Logout</a>
              <form id="logout-form" action='{% url 'accounts:logout'%}' method="post" style="display:none;">
                {% csrf_token %}
              </form>

              {% comment %} <a href='{% url 'accounts:logout'%}'> Log Out </a> {% endcomment %}
              <p>{{request.user}}</p>

              <p><a href="{% url 'blog:blog_single' pid=post.id %}"> back to blog page </a></p>
              
              <p class="h1 text-center mt-3 mb-4 pb-3 text-primary">
                {% comment %} <i class="fas fa-check-square me-1"></i> {% endcomment %}
                Leave Your Comments ....
              </p>
              

              <div class="pb-2">
                <div class="card">
                  <div class="card-body">
                    <div class="d-flex flex-row align-items-center">
                      <form action="{% url 'comment:task' pid=post.id %}" method="post">
                        {% csrf_token %}
                        {{form.author}}
                        {% comment %} {{form.post}} {% endcomment %}
                        <input type="text" name='title' class="form-control form-control-lg" id="exampleFormControlInput1" placeholder="Add new...">
                        <input type="hidden" name='post' value={{post.id}} class="form-control form-control-lg" id="exampleFormControlInput1" placeholder="Add new...">
                        <button type="submit" class="btn btn-primary">Add</button>
                      </form>
                    </div>
                    
                  </div>
                </div>
              </div>

              <hr class="my-4">

              {% comment %} <div class="d-flex justify-content-end align-items-center mb-4 pt-2 pb-3">
                <p class="small mb-0 me-2 text-muted">Filter</p>
                <select class="select">
                  <option value="1">All</option>
                  <option value="2">Completed</option>
                  <option value="3">Active</option>
                  <option value="4">Has due date</option>
                </select>
                <p class="small mb-0 ms-4 me-2 text-muted">Sort</p>
                <select class="select">
                  <option value="1">Added date</option>
                  <option value="2">Due date</option>
                </select>
                <a href="#!" style="color: #23af89;" data-mdb-toggle="tooltip" title="Ascending"><i class="fas fa-sort-amount-down-alt ms-2"></i></a>
              </div> {% endcomment %}
              
              {% for task in tasks %}
              <ul class="list-group list-group-horizontal rounded-0 bg-transparent">
                
                <li class="list-group-item d-flex align-items-center ps-0 pe-3 py-1 rounded-0 border-0 bg-transparent">
                  {% if task.author.user == request.user %}
                  <a href="{% url 'comment:task-complete' pid=post.id pk=task.id %}" title="complete comment">
                    <div class="form-check"> 
                      <input
                      class="form-check-input me-0"
                      type="checkbox"
                      value=''
                      id="flexCheckChecked1"
                      aria-label="..."
                      {% if task.status == True %}
                      checked
                      {% endif %}
                      disabled
                      />
                    </div>
                  </a>
                  {% endif %}
                </li>
                 
                <li class="list-group-item px-3 py-1 d-flex align-items-center flex-grow-1 border-0 bg-transparent">
                  <p class="lead fw-normal mb-0">{{task.id}} - {{task.title}} </p>
                </li>
                <li class="list-group-item ps-3 pe-0 py-1 rounded-0 border-0 bg-transparent">
                  
                  <div class="d-flex flex-row justify-content-end mb-1">   
                    {% if task.author.user == request.user %}           
                    <a href="{% url 'comment:task-edit' pid=post.id pk=task.id %}" class="text-info" data-mdb-toggle="tooltip" title="Edit comment"><i class="fas fa-pencil-alt me-3"></i></a>
                    <a href="{% url 'comment:task-delete' pid=post.id pk=task.id %}" class="text-danger" data-mdb-toggle="tooltip" title="Delete comment"><i class="fas fa-trash-alt"></i></a> 
                    {% endif %}
                  </div>
                  <div class="text-end text-muted">
                    <a href="#!" class="text-muted" data-mdb-toggle="tooltip" title="Created date">
                      <p class="small mb-0"><i class="fas fa-info-circle me-2"></i>{{task.created_date}}</p></a>
                      <p>{% if task.author.image %}<img src="{{ task.author.image.url }}" alt="Profile Image" style="width:80px; height:80px; border-radius:50%;"> {% endif %}</p>
                      <p> {{task.author.first_name}} </p>
                  </div>
                </li>
              </ul>
              {% endfor %}

            </div>
          </div>
        </div>
      </div>
    </div>
  </section>
  <!-- End your project here-->

  <!-- MDB -->
  <script type="text/javascript" src= "{% static "comment/js/mdb.min.js" %}"></script>
  <!-- Custom scripts -->
  <script type="text/javascript"></script>
</body>

</html>

core/templates/comment/comment_complete.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
  <meta http-equiv="x-ua-compatible" content="ie=edge" />
  <title>Edit Status</title>
  <!-- MDB icon -->
  <link rel="icon" href="{% static "comment/img/mdb-favicon.ico" %}" type="image/x-icon" />
  <!-- Font Awesome -->
  <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.15.2/css/all.css" />
  <!-- Google Fonts Roboto -->
  <link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Roboto:wght@300;400;500;700;900&display=swap" />
  <!-- MDB -->
  <link rel="stylesheet" href="{% static "comment/css/bootstrap-to-do-list.min.css" %}" />
</head>

<body>
  <!-- Start your project here-->
  <style>
    #list1 .form-control {
      border-color: transparent;
    }
    #list1 .form-control:focus {
      border-color: transparent;
      box-shadow: none;
    }
    #list1 .select-input.form-control[readonly]:not([disabled]) {
      background-color: #fbfbfb;
    }
  </style>
  <section class="vh-100">
    <div class="container py-5 h-100">
      <div class="row d-flex justify-content-center align-items-center h-100">
        <div class="col">
          <div class="card" id="list1" style="border-radius: .75rem; background-color: #eff1f2;">
            <div class="card-body py-4 px-4 px-md-5">

              <p class="h1 text-center mt-3 mb-4 pb-3 text-primary">
                
                Edit Status
                {% comment %} - {{request.user}} {% endcomment %}
              </p>

              <div class="pb-2">
                <div class="card">
                  <div class="card-body">
                    <div class="d-flex flex-row align-items-center">
                        <form method="post">{% csrf_token %}
                            {% comment %} {{ form.as_p }} {% endcomment %}
                            <input type="text" name='status' value= {{task.status}} class="form-control form-control-lg" id="exampleFormControlInput1" placeholder="edit ...">
                            <button type="submit" class="btn btn-primary">Toggle</button>
                        </form>
                    </div>
                    
                  </div>
                </div>
              </div>

              <hr class="my-4">



            </div>
          </div>
        </div>
      </div>
    </div>
  </section>
  <!-- End your project here-->

  <!-- MDB -->
  <script type="text/javascript" src= "{% static "comment/js/mdb.min.js" %}"></script>
  <!-- Custom scripts -->
  <script type="text/javascript"></script>
</body>

</html>

core/templates/comment/task.html
{%load static%}

<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
  <meta http-equiv="x-ua-compatible" content="ie=edge" />
  <title>comment</title>
  <!-- MDB icon -->
  <link rel="icon" href="{% static "comment/img/mdb-favicon.ico" %}" type="image/x-icon" />
  <!-- Font Awesome -->
  <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.15.2/css/all.css" />
  <!-- Google Fonts Roboto -->
  <link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Roboto:wght@300;400;500;700;900&display=swap" />
  <!-- MDB -->
  <link rel="stylesheet" href="{% static "comment/css/bootstrap-to-do-list.min.css" %}" />
</head>

<body>
  <!-- Start your project here-->
  <style>
    #list1 .form-control {
      border-color: transparent;
    }
    #list1 .form-control:focus {
      border-color: transparent;
      box-shadow: none;
    }
    #list1 .select-input.form-control[readonly]:not([disabled]) {
      background-color: #fbfbfb;
    }
  </style>
  <section class="vh-100">
    <div class="container py-5 h-100">
      <div class="row d-flex justify-content-center align-items-center h-100">
        <div class="col">
          <div class="card" id="list1" style="border-radius: .75rem; background-color: #eff1f2;">
            <div class="card-body py-4 px-4 px-md-5">

              <a href="#" onclick="document.getElementById('logout-form').submit();" class="primary-btn">Logout</a>
              <form id="logout-form" action='{% url 'accounts:logout'%}' method="post" style="display:none;">
                {% csrf_token %}
              </form>

              {% comment %} <a href='{% url 'accounts:logout'%}'> Log Out </a> {% endcomment %}
              <p>{{request.user}}</p>
              <p class="h1 text-center mt-3 mb-4 pb-3 text-primary">
                {% comment %} <i class="fas fa-check-square me-1"></i> {% endcomment %}
                Leave Your Comments ....
              </p>
              

              <div class="pb-2">
                <div class="card">
                  <div class="card-body">
                    <div class="d-flex flex-row align-items-center">
                      <form action="{% url 'comment:task' pid=post.id %}" method="post">
                        {% csrf_token %}
                        {{form.author}}
                        {% comment %} {{form.post}} {% endcomment %}
                        <input type="text" name='title' class="form-control form-control-lg" id="exampleFormControlInput1" placeholder="Add new...">
                        <input type="hidden" name='post' value={{post.id}} class="form-control form-control-lg" id="exampleFormControlInput1" placeholder="Add new...">
                        <button type="submit" class="btn btn-primary">Add</button>
                      </form>
                    </div>
                    
                  </div>
                </div>
              </div>

              <hr class="my-4">

              {% comment %} <div class="d-flex justify-content-end align-items-center mb-4 pt-2 pb-3">
                <p class="small mb-0 me-2 text-muted">Filter</p>
                <select class="select">
                  <option value="1">All</option>
                  <option value="2">Completed</option>
                  <option value="3">Active</option>
                  <option value="4">Has due date</option>
                </select>
                <p class="small mb-0 ms-4 me-2 text-muted">Sort</p>
                <select class="select">
                  <option value="1">Added date</option>
                  <option value="2">Due date</option>
                </select>
                <a href="#!" style="color: #23af89;" data-mdb-toggle="tooltip" title="Ascending"><i class="fas fa-sort-amount-down-alt ms-2"></i></a>
              </div> {% endcomment %}
              
              {% for task in tasks %}
              <ul class="list-group list-group-horizontal rounded-0 bg-transparent">
                <li class="list-group-item d-flex align-items-center ps-0 pe-3 py-1 rounded-0 border-0 bg-transparent">
                  <a href="{% url 'comment:task-complete' pid=post.id pk=task.id %}" title="complete todo">
                    <div class="form-check"> 
                      <input
                      class="form-check-input me-0"
                      type="checkbox"
                      value=''
                      id="flexCheckChecked1"
                      aria-label="..."
                      {% if task.status == True %}
                      checked
                      {% endif %}
                      disabled
                      />
                    </div>
                  </a>
                </li>
                <li class="list-group-item px-3 py-1 d-flex align-items-center flex-grow-1 border-0 bg-transparent">
                  <p class="lead fw-normal mb-0">{{task.id}} - {{task.title}} </p>
                </li>
                <li class="list-group-item ps-3 pe-0 py-1 rounded-0 border-0 bg-transparent">
                  <div class="d-flex flex-row justify-content-end mb-1">              
                    <a href="{% url 'comment:task-edit' pid=post.id pk=task.id %}" class="text-info" data-mdb-toggle="tooltip" title="Edit todo"><i class="fas fa-pencil-alt me-3"></i></a>
                    <a href="{% url 'comment:task-delete' pid=post.id pk=task.id %}" class="text-danger" data-mdb-toggle="tooltip" title="Delete todo"><i class="fas fa-trash-alt"></i></a> 
                  </div>
                  <div class="text-end text-muted">
                    <a href="#!" class="text-muted" data-mdb-toggle="tooltip" title="Created date">
                      <p class="small mb-0"><i class="fas fa-info-circle me-2"></i>{{task.created_date}}</p></a>
                      <p><img src="{{ task.author.image.url }}" alt="Profile Image" style="width:80px; height:80px; border-radius:50%;"></p>
                      <p> {{task.author}} </p>
                  </div>
                </li>
              </ul>
              {% endfor %}

            </div>
          </div>
        </div>
      </div>
    </div>
  </section>
  <!-- End your project here-->

  <!-- MDB -->
  <script type="text/javascript" src= "{% static "comment/js/mdb.min.js" %}"></script>
  <!-- Custom scripts -->
  <script type="text/javascript"></script>
</body>

</html>