core/accounts/urls.py
from django.urls import path, include
from .views import SignUpView, ProfileView
from django.views.generic import RedirectView
from .views import MyLoginView, swagger_logout_view
from django.contrib.auth.views import LogoutView

app_name = "accounts"

urlpatterns = [
    path("", RedirectView.as_view(url="blog/", query_string=True, permanent=False)),
    # path('',include('django.contrib.auth.urls')),
    path("login/", MyLoginView.as_view(), name="login"),
    path(
        "logout/",
        LogoutView.as_view(next_page="/accounts/login/"),
        name="logout",
        kwargs={"swagger_schema": None},
    ),
    path("signup/", SignUpView.as_view(), name="signup"),
    path("<int:pk>/profile/", ProfileView.as_view(), name="profile"),
    path("api/v1/", include("accounts.api.v1.urls")),
    # Swagger-only URL (appears in Swagger UI)
    path("swagger-logout/", swagger_logout_view, name="swagger-logout"),
]

core/blog/urls.py
from django.urls import path
from .views import BlogHomeView, BlogSingleView
from blog.feeds import LatestEntriesFeed

app_name = "blog"

urlpatterns = [
    path("", BlogHomeView.as_view(), name="blog_home"),
    path("category/<str:cat_name>/", BlogHomeView.as_view(), name="category"),
    path("author/<str:author>/", BlogHomeView.as_view(), name="author"),
    path("search/", BlogHomeView.as_view(), name="search"),
    path("tag/<str:tag_name>/", BlogHomeView.as_view(), name="tag"),
    path("<int:pid>", BlogSingleView.as_view(), name="blog_single"),
    path("rss/feed/", LatestEntriesFeed()),
]

core/core/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from rest_framework import permissions
from drf_yasg.views import get_schema_view
from drf_yasg import openapi
from django.contrib.sitemaps.views import sitemap
from website.sitemaps import StaticViewSitemap
from blog.sitemaps import BlogSitemap
import debug_toolbar

sitemaps = {"static": StaticViewSitemap, "blog": BlogSitemap}


# for api document
schema_view = get_schema_view(
    openapi.Info(
        title="Blog API",
        default_version="v1",
        description="API documentation",
        terms_of_service="https://www.google.com/policies/terms/",
        contact=openapi.Contact(email="a_anvari@ymail.com"),
        license=openapi.License(name="BSD License"),
    ),
    public=True,
    permission_classes=(permissions.AllowAny,),
)

urlpatterns = [
    path("admin/", admin.site.urls),
    path("comment/", include("comment.urls")),
    path("accounts/", include("accounts.urls")),
    path("", include("accounts.urls")),
    path("api-auth/", include("rest_framework.urls")),
    path("website/", include("website.urls")),
    path("blog/", include("blog.urls")),
    path("post/", include("post.urls")),
    # your API endpoints here
    path(
        "swagger/",
        schema_view.with_ui("swagger", cache_timeout=0),
        name="schema-swagger-ui",
    ),
    path(
        "redoc/",
        schema_view.with_ui("redoc", cache_timeout=0),
        name="schema-redoc",
    ),
    path(
        "swagger.json",
        schema_view.without_ui(cache_timeout=0),
        name="schema-json",
    ),
    path(
        "sitemap.xml",
        sitemap,
        {"sitemaps": sitemaps},
        name="django.contrib.sitemaps.views.sitemap",
    ),
    path("robots.txt", include("robots.urls")),
    path("__debug__/", include(debug_toolbar.urls)),
    path("summernote/", include("django_summernote.urls")),
    path("captcha/", include("captcha.urls")),
    path("maintenance/", include("config.urls")),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

core/website/urls.py
from django.urls import path
from .views import IndexView, AboutView, ContactView, NotificationView, NewsletterView

app_name = "website"

urlpatterns = [
    path("", IndexView.as_view(), name="index"),
    path("about", AboutView.as_view(), name="about"),
    path("contact", ContactView.as_view(), name="contact"),
    path("notification", NotificationView.as_view(), name="notification"),
    path("newsletter", NewsletterView.as_view(), name="newsletter"),
]

core/templates/base2-2.html
<!DOCTYPE html>
{% extends 'notification.html' %}
{%load static%}
{%load compress%}
{%block content2%}

<html lang="zxx">

<head>
    <meta charset="UTF-8">
    <meta name="description" content="Foodeiblog Template">
    <meta name="keywords" content="Foodeiblog, unica, creative, html">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Foodeiblog | Template</title>

    <!-- Google Font -->
    <link href="https://fonts.googleapis.com/css?family=Nunito+Sans:300,400,600,700,800,900&display=swap"
        rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Unna:400,700&display=swap" rel="stylesheet">

    <!-- Css Styles -->
    {% compress css %}
    <link rel="stylesheet" href="{% static "template2/css/bootstrap.min.css" %}" type="text/css">
    <link rel="stylesheet" href="{% static "template2/css/font-awesome.min.css" %}"  type="text/css">
    <link rel="stylesheet" href="{% static "template2/css/elegant-icons.css" %}" type="text/css">
    <link rel="stylesheet" href="{% static "template2/css/owl.carousel.min.css" %}" type="text/css">
    <link rel="stylesheet" href="{% static "template2/css/slicknav.min.css" %}" type="text/css">
    <link rel="stylesheet" href="{% static "template2/css/style.css" %}" type="text/css">
    {% endcompress %}

</head>
<body>
    <!-- Page Preloder -->
    <div id="preloder">
        <div class="loader"></div>
    </div>


    {%block content%}




    {%endblock%}


    <!-- Js Plugins -->
    {% compress js %} 
    <script src="{% static "template2/js/jquery-3.3.1.min.js" %}"></script>
    <script src="{% static "template2/js/bootstrap.min.js" %}"></script>
    <script src="{% static "template2/js/jquery.slicknav.js" %}"></script>
    <script src="{% static "template2/js/owl.carousel.min.js" %}"></script>
    <script src="{% static "template2/js/main.js" %}"></script>
    {% endcompress %}
    
</body>

</html>

{%endblock%}

core/templates/base2.html
<!DOCTYPE html>
{% extends 'notification.html' %}
{%load static%}
{%load compress%}
{%block content2%}

<html lang="zxx">

<head>
    <meta charset="UTF-8">
    <meta name="description" content="Foodeiblog Template">
    <meta name="keywords" content="Foodeiblog, unica, creative, html">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Foodeiblog | Template</title>

    <!-- Google Font -->
    <link href="https://fonts.googleapis.com/css?family=Nunito+Sans:300,400,600,700,800,900&display=swap"
        rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Unna:400,700&display=swap" rel="stylesheet">

    <!-- Css Styles -->
    {% compress css %}
    <link rel="stylesheet" href="{% static "template2/css/bootstrap.min.css" %}" type="text/css">
    <link rel="stylesheet" href="{% static "template2/css/font-awesome.min.css" %}"  type="text/css">
    <link rel="stylesheet" href="{% static "template2/css/elegant-icons.css" %}" type="text/css">
    <link rel="stylesheet" href="{% static "template2/css/owl.carousel.min.css" %}" type="text/css">
    <link rel="stylesheet" href="{% static "template2/css/slicknav.min.css" %}" type="text/css">
    <link rel="stylesheet" href="{% static "template2/css/style.css" %}" type="text/css">
    {% endcompress %}

</head>
<body>
    <!-- Page Preloder -->
    <div id="preloder">
        <div class="loader"></div>
    </div>

    <!-- Humberger Begin -->
    <div class="humberger__menu__overlay"></div>
    <div class="humberger__menu__wrapper">
        <div class="humberger__menu__logo">
            <a href="{% url "website:index" %}"><img src="{% static "template2/img/humberger/humberger-logo.png" %}" alt=""></a>
        </div>
        <nav class="humberger__menu__nav mobile-menu">
            <ul>
                <li><a href="{% url "website:index" %}">Home</a></li>
                <li><a href="{% url "blog:blog_home" %}">Blog</a></li>
                <li><a href="{% url "website:about" %}">About</a></li>
                <li><a href="{% url "website:contact" %}">Contact</a></li>
                <li> 
                    {% if request.user.is_authenticated %}
                    
                        <!--for logoutview in django 5.2 -->
                        <a href="#" onclick="document.getElementById('logout-form').submit();">Log out</a>
                        <form id="logout-form" action="{% url 'accounts:logout' %}?next={{request.path}}" method="post" style="display:none;">
                        {% csrf_token %}
                        </form>
                        {% comment %} <a href="{% url 'accounts:logout' %}?next={{request.path}}">logout</a> {% endcomment %}

                        <p>logged in as {{request.user}}</p>
                        <p><a href="{% url 'accounts:profile' pk=request.user.id %}?next={{request.path}}">your profile</a></p>
                    {% else %}
                    <a href="{% url 'accounts:login' %}?next={{request.path}}">login / signUp</a>
                    {% endif %}  
                </li>
            </ul>
        </nav>
        <div id="mobile-menu-wrap"></div>
        <div class="humberger__menu__about">
            <div class="humberger__menu__title sidebar__item__title">
                <h6>About me</h6>
            </div>
            <img src="{% static "template2/img/humberger/humberger-about.jpg" %}" alt="">
            <h6>Hi every one! I,m Lena Mollein.</h6>
            <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et
                dolore magna aliqua.</p>
            <div class="humberger__menu__about__social sidebar__item__follow__links">
                <a href="#"><i class="fa fa-facebook"></i></a>
                <a href="#"><i class="fa fa-twitter"></i></a>
                <a href="#"><i class="fa fa-youtube-play"></i></a>
                <a href="#"><i class="fa fa-instagram"></i></a>
                <a href="#"><i class="fa fa-envelope-o"></i></a>
            </div>
        </div>
        <div class="humberger__menu__subscribe">
            <div class="humberger__menu__title sidebar__item__title">
                <h6>Subscribe</h6>
            </div>
            {% include 'website/website-subscribe.html' %}
        </div>
    </div>
    <!-- Humberger End -->

    <!-- Header Section Begin -->
    <header class="header">
        <div class="header__top">
            <div class="container">
                <div class="row">
                    <div class="col-lg-2 col-md-1 col-6 order-md-1 order-1">
                        <div class="header__humberger">
                            <i class="fa fa-bars humberger__open"></i>
                        </div>
                    </div>
                    <div class="col-lg-8 col-md-10 order-md-2 order-3">
                        <nav class="header__menu">
                            <ul>
                                <li class="active"><a href="{% url "website:index" %}">Home</a></li>
                                <li><a href="{% url "blog:blog_home" %}">Blog</a></li>
                                <li><a href="{% url "website:about" %}">About</a></li>
                                <li><a href="{% url "website:contact" %}">Contact</a></li>
                            </ul>
                        </nav>
                    </div>
                    <div class="col-lg-2 col-md-1 col-6 order-md-3 order-2">
                        <div class="header__search">
                            <i class="fa fa-search search-switch"></i>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="container">
            <div class="row">
                <div class="col-lg-3 col-md-3">
                    <div class="header__btn">
                        {% if request.user.is_authenticated %}

                        <a href="#" onclick="document.getElementById('logout-form').submit();" class="primary-btn">Logout</a>
                        <form id="logout-form" action="{% url 'accounts:logout' %}?next={{request.path}}" method="post" style="display:none;">
                        {% csrf_token %}
                        </form>

                        {% comment %} <a href="{% url 'accounts:logout' %}?next={{request.path}}" class="primary-btn">logout</a> {% endcomment %}
                        <p>logged in as {{request.user}}</p>
                        <p><a href="{% url 'accounts:profile' pk=request.user.id %}?next={{request.path}}">your profile</a></p>
                        {% else %}
                        <a href="{% url 'accounts:login' %}?next={{request.path}}" class="primary-btn">login / signUp</a>
                        {% endif %}  
                    </div>
                </div>
                <div class="col-lg-6 col-md-6">
                    <div class="header__logo">
                        <a href="{% url "website:index" %}"><img src="{% static "template2/img/logo.png" %}" alt=""></a>
                    </div>
                </div>
                <div class="col-lg-3 col-md-3">
                    <div class="header__social">
                        <a href="#"><i class="fa fa-facebook"></i></a>
                        <a href="#"><i class="fa fa-twitter"></i></a>
                        <a href="#"><i class="fa fa-youtube-play"></i></a>
                        <a href="#"><i class="fa fa-instagram"></i></a>
                        <a href="#"><i class="fa fa-envelope-o"></i></a>
                    </div>
                </div>
            </div>
        </div>
    </header>
    <!-- Header Section End -->

    {%block content%}




    {%endblock%}

    <!-- Footer Section Begin -->
    <footer class="footer">
        <div class="container-fluid">
            <div class="footer__instagram">
                <div class="footer__instagram__avatar">
                    <div class="footer__instagram__avatar--pic">
                        <img src="{% static "template2/img/footer/instagram-avatar.jpg" %}" alt="">
                    </div>
                    <div class="footer__instagram__avatar--text">
                        <h5>@ foodieblog</h5>
                        <span>23,7k follower</span>
                    </div>
                </div>
                <div class="row">
                    <div class="col-lg-2 col-md-2 col-sm-4 col-6">
                        <div class="footer__instagram__item set-bg" data-setbg="{% static "template2/img/footer/ip-1.jpg" %}"></div>
                    </div>
                    <div class="col-lg-2 col-md-2 col-sm-4 col-6">
                        <div class="footer__instagram__item set-bg" data-setbg="{% static "template2/img/footer/ip-2.jpg" %}"></div>
                    </div>
                    <div class="col-lg-2 col-md-2 col-sm-4 col-6">
                        <div class="footer__instagram__item set-bg" data-setbg="{% static "template2/img/footer/ip-3.jpg" %}"></div>
                    </div>
                    <div class="col-lg-2 col-md-2 col-sm-4 col-6">
                        <div class="footer__instagram__item set-bg" data-setbg="{% static "template2/img/footer/ip-4.jpg" %}"></div>
                    </div>
                    <div class="col-lg-2 col-md-2 col-sm-4 col-6">
                        <div class="footer__instagram__item set-bg" data-setbg="{% static "template2/img/footer/ip-5.jpg" %}"></div>
                    </div>
                    <div class="col-lg-2 col-md-2 col-sm-4 col-6">
                        <div class="footer__instagram__item set-bg" data-setbg="{% static "template2/img/footer/ip-6.jpg" %}"></div>
                    </div>
                </div>
            </div>
        </div>
        <div class="container">
            <div class="row">
                <div class="col-lg-12">
                    <div class="footer__text">
                        <div class="footer__logo">
                            <a href="{% url "website:index" %}"><img src="{% static "template2/img/logo.png" %}" alt=""></a>
                        </div>
                        <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt
                            ut<br /> labore et dolore magna aliqua. Quis ipsum suspendisse ultrices gravida. Risus
                            commodo viverra<br /> maecenas accumsan lacus vel facilisis. </p>
                        <div class="footer__social">
                            <a href="#"><i class="fa fa-facebook"></i></a>
                            <a href="#"><i class="fa fa-twitter"></i></a>
                            <a href="#"><i class="fa fa-instagram"></i></a>
                            <a href="#"><i class="fa fa-youtube-play"></i></a>
                            <a href="#"><i class="fa fa-envelope-o"></i></a>
                        </div>
                    </div>
                    <div class="footer__copyright">
                        <p><!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->
  Copyright &copy;<script>document.write(new Date().getFullYear());</script> All rights reserved | This template is made with <i class="fa fa-heart" aria-hidden="true"></i> by <a href="https://colorlib.com" target="_blank">Colorlib</a>
  <!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. --></p>
                    </div>
                </div>
            </div>
        </div>
    </footer>
    <!-- Footer Section End -->

    <!-- Search Begin -->
    <div class="search-model">
        <div class="h-100 d-flex align-items-center justify-content-center">
            <div class="search-close-switch">+</div>
            <form class="search-model-form">
                <input type="text" id="search-input" placeholder="Search here.....">
            </form>
        </div>
    </div>
    <!-- Search End -->

    <!-- Js Plugins -->
    {% compress js %} 
    <script src="{% static "template2/js/jquery-3.3.1.min.js" %}"></script>
    <script src="{% static "template2/js/bootstrap.min.js" %}"></script>
    <script src="{% static "template2/js/jquery.slicknav.js" %}"></script>
    <script src="{% static "template2/js/owl.carousel.min.js" %}"></script>
    <script src="{% static "template2/js/main.js" %}"></script>
    {% endcompress %}
    
</body>

</html>

{%endblock%}

core/templates/notification.html
<html>
<body>

    {% if messages %}
    {% for message in messages %}
      <div id="message_container" class="alert {% if message.tags %} alert-{{ message.tags }}{% endif %}" style="width:50%;text-align:center;position:relative;
      left:23%;top:5px">{{ message|safe }}</div>
    {% endfor %}
    {% endif %}

    {% if form.errors %}
    <div class="alert alert-error">
      <h4>Please fix the following errors</h4>
      <ul>
        {% for field in form %}
          {% if field.errors %}
            {% for error in field.errors %}
              <li><a href="#id_{{ field.name }}" class="error">{{ error|escape }}</a></li>
            {% endfor %}
          {% endif %}
        {% endfor %}
      </ul>
      {% if form.non_field_errors %}
        {{ form.non_field_errors }}
      {% endif %}
    </div>
    {% endif %}

    <script>
        var message_ele = document.getElementById("message_container");
        setTimeout(function(){ 
        message_ele.style.display = "none"; 
        }, 5000);
    </script>     

{%block content2%}

{%endblock%}

</body>
</html>