core/blog/urls.py
from django.urls import path
from .views import BlogHomeView, BlogSingleView
from blog.feeds import LatestEntriesFeed

app_name = "blog"

urlpatterns = [
    path("", BlogHomeView.as_view(), name="blog_home"),
    path("category/<str:cat_name>/", BlogHomeView.as_view(), name="category"),
    path("author/<str:author>/", BlogHomeView.as_view(), name="author"),
    path("search/", BlogHomeView.as_view(), name="search"),
    path("tag/<str:tag_name>/", BlogHomeView.as_view(), name="tag"),
    path("<int:pid>", BlogSingleView.as_view(), name="blog_single"),
    path("rss/feed/", LatestEntriesFeed()),
]

core/comment/urls.py
from django.urls import path, include
from .views import (
    TaskEditView,
    TaskDeleteView,
    TaskCompleteView,
    TaskView,
    test,
    weather,
    WeatherView,
)

app_name = "comment"

urlpatterns = [
    path("<int:pid>", TaskView.as_view(), name="task"),
    path("<int:pid>/<int:pk>/edit/", TaskEditView.as_view(), name="task-edit"),
    path("<int:pid>/<int:pk>/delete/", TaskDeleteView.as_view(), name="task-delete"),
    path(
        "<int:pid>/<int:pk>/complete/",
        TaskCompleteView.as_view(),
        name="task-complete",
    ),
    path("api/v1/", include("comment.api.v1.urls")),
    # Test Celery:
    path("test/", test, name="test"),
    # Test Redis for cache:
    path("weather/", weather, name="weather"),
    # Show graphical weather data:
    path("weather_show/", WeatherView.as_view(), name="weather_show"),
]

core/core/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from rest_framework import permissions
from drf_yasg.views import get_schema_view
from drf_yasg import openapi
from django.contrib.sitemaps.views import sitemap
from website.sitemaps import StaticViewSitemap
from blog.sitemaps import BlogSitemap
import debug_toolbar

sitemaps = {"static": StaticViewSitemap, "blog": BlogSitemap}


# for api document
schema_view = get_schema_view(
    openapi.Info(
        title="Blog API",
        default_version="v1",
        description="API documentation",
        terms_of_service="https://www.google.com/policies/terms/",
        contact=openapi.Contact(email="a_anvari@ymail.com"),
        license=openapi.License(name="BSD License"),
    ),
    public=True,
    permission_classes=(permissions.AllowAny,),
)

urlpatterns = [
    path("admin/", admin.site.urls),
    path("comment/", include("comment.urls")),
    path("accounts/", include("accounts.urls")),
    path("", include("accounts.urls")),
    path("api-auth/", include("rest_framework.urls")),
    path("website/", include("website.urls")),
    path("blog/", include("blog.urls")),
    path("post/", include("post.urls")),
    # your API endpoints here
    path(
        "swagger/",
        schema_view.with_ui("swagger", cache_timeout=0),
        name="schema-swagger-ui",
    ),
    path(
        "redoc/",
        schema_view.with_ui("redoc", cache_timeout=0),
        name="schema-redoc",
    ),
    path(
        "swagger.json",
        schema_view.without_ui(cache_timeout=0),
        name="schema-json",
    ),
    path(
        "sitemap.xml",
        sitemap,
        {"sitemaps": sitemaps},
        name="django.contrib.sitemaps.views.sitemap",
    ),
    path("robots.txt", include("robots.urls")),
    path("__debug__/", include(debug_toolbar.urls)),
    path("summernote/", include("django_summernote.urls")),
    path("captcha/", include("captcha.urls")),
    path("maintenance/", include("config.urls")),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

core/post/urls.py
from django.urls import path, include
from .views import (
    PostEditView,
    PostDeleteView,
    PostCompleteView,
    PostView,
)

app_name = "post"

urlpatterns = [
    path("", PostView.as_view(), name="post"),
    path("<int:pk>/edit/", PostEditView.as_view(), name="post-edit"),
    path("<int:pk>/delete/", PostDeleteView.as_view(), name="post-delete"),
    path(
        "<int:pk>/complete/",
        PostCompleteView.as_view(),
        name="post-complete",
    ),
    path("api/v1/", include("post.api.v1.urls")),
]

core/website/urls.py
from django.urls import path
from .views import IndexView, AboutView, ContactView, NotificationView, NewsletterView

app_name = "website"

urlpatterns = [
    path("", IndexView.as_view(), name="index"),
    path("about", AboutView.as_view(), name="about"),
    path("contact", ContactView.as_view(), name="contact"),
    path("notification", NotificationView.as_view(), name="notification"),
    path("newsletter", NewsletterView.as_view(), name="newsletter"),
]

core/blog/models.py
from django.db import models
from django.urls import reverse
from taggit.managers import TaggableManager


# Create your models here.
class Category(models.Model):
    name = models.CharField(max_length=255)

    def __str__(self):
        return self.name


class Post(models.Model):
    image = models.ImageField(upload_to="blog/", blank=True, null=True, default="blog/cl-1.jpg")
    author = models.ForeignKey("accounts.Profile", on_delete=models.SET_NULL, null=True)
    title = models.CharField(max_length=255)
    content = models.TextField()
    tags = TaggableManager(blank=True)
    category = models.ManyToManyField(Category, blank=True)
    counted_views = models.IntegerField(default=0)
    status = models.BooleanField(default=False)
    login_require = models.BooleanField(default=False)
    published_date = models.DateTimeField(auto_now_add=True)
    created_date = models.DateTimeField(auto_now_add=True)
    updated_date = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.title

    class Meta:
        ordering = ["id"]

    def get_absolute_url(self):
        return reverse("blog:blog_single", kwargs={"pid": self.id})

core/blog/forms.py
# from django import forms
# from blog.models import Comment

# class CommentForm(forms.ModelForm):

#     class Meta:
#         model = Comment
#         fields = ['post','name','subject','email','message']

core/blog/views.py
from .models import Post
from django.utils import timezone
from django.views.generic import DetailView
from django.db.models import F
from django.urls import reverse_lazy
from django.views.generic import ListView
from django.contrib.auth.mixins import (
    LoginRequiredMixin,
)


# customize LoginRequiredMixin for redirect to login page first
class MyLoginRequiredMixin(LoginRequiredMixin):
    def get_login_url(self):
        return reverse_lazy("accounts:login")


class BlogHomeView(MyLoginRequiredMixin, ListView):
    model = Post
    template_name = "blog/blog-home2.html"
    context_object_name = "posts"
    paginate_by = 2

    def get_queryset(self):
        queryset = Post.objects.filter(published_date__lte=timezone.now(), status=True)

        cat_name = self.kwargs.get("cat_name")
        author = self.kwargs.get("author")
        tag_name = self.kwargs.get("tag_name")
        s = self.request.GET.get("s")

        if tag_name:
            queryset = queryset.filter(tags__name=tag_name)
        if cat_name:
            queryset = queryset.filter(category__name=cat_name)
        if author:
            queryset = queryset.filter(author__username=author)
        if s:
            queryset = queryset.filter(content__contains=s)

        return queryset


class BlogSingleView(MyLoginRequiredMixin, DetailView):
    model = Post
    template_name = "blog/blog-single2.html"
    context_object_name = "post"
    pk_url_kwarg = "pid"

    def get_queryset(self):
        return Post.objects.filter(status=True, published_date__lte=timezone.now())

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        post = self.object

        # Next post (newer)
        post_after = (
            Post.objects.filter(
                status=True,
                published_date__lte=timezone.now(),
                published_date__gt=post.published_date,
            )
            .order_by("published_date")
            .first()
        )

        # Previous post (older)
        post_pre = (
            Post.objects.filter(
                status=True,
                published_date__lte=timezone.now(),
                published_date__lt=post.published_date,
            )
            .order_by("-published_date")
            .first()
        )

        context.update(
            {
                "post_after": post_after,
                "post_pre": post_pre,
                "after": post_after is not None,
                "pre": post_pre is not None,
            }
        )

        return context

    def get(self, request, *args, **kwargs):
        self.object = self.get_object()

        # Count views safely
        Post.objects.filter(pk=self.object.pk).update(
            counted_views=F("counted_views") + 1
        )
        self.object.refresh_from_db()

        return super().get(request, *args, **kwargs)

core/templates/blog/blog-home2.html
{%extends 'base2.html'%}
{%load static%}
{% load blog_tags %}
{% load humanize %}

{%block content%}


    <!-- Categories Section Begin -->
    <section class="categories categories-grid spad">
        <div class="categories__post">
            <div class="container">
                <div class="categories__grid__post">
                    <div class="row">
                        <div class="col-lg-8 col-md-8">
                            <div class="breadcrumb__text">
                                <div class="breadcrumb__option">
                                    <a href="{% url "website:index" %}">Home</a>
                                    <span>Blog</span>
                                </div>
                            </div>
                            
                                <div class="sidebar__item__categories">
                                    <div class="sidebar__item__title">
                                        <a href="{% url "post:post" %}"><h6>Create Your Posts</h6></a>
                                        <h6></h6>
                                    </div>
                                </div>


                            {%for post in posts%}
                            <div class="categories__list__post__item">
                                <div class="row">
                                    
                                    <div class="col-lg-6 col-md-6">
                                        <div class="categories__post__item__pic set-bg"
                                            data-setbg={{post.image.url}}>
                                            <div class="post__meta">
                                                <h4>{{post.published_date|date:'d'}}</h4>
                                                <span>{{post.published_date|date:'M'}}</span>
                                            </div>
                                        </div>
                                    </div>
                                    <div class="col-lg-6 col-md-6">
                                        <div class="categories__post__item__text">
                                            <span class="post__label">
                                                {% for cat in post.category.all %}
                                                <a href="{% url "blog:category" cat_name=cat.name %}">{{cat.name}} {%if not forloop.last%} | {%endif%}</a>
                                                {% endfor %}
                                            </span>
                                            <h3><a href="{% url "blog:blog_single" pid=post.id %}">{{post.title}}</a></h3>
                                            <ul class="post__widget">
                                                <li>by <span>{{post.author}}</span></li>
                                                <li>{{post.counted_views}} views</li>
                                                <li>{% comment_count post %} Comments</li>
                                                <li>{{post.published_date|naturalday}}</li>
                                            </ul>
                                            <p>{{post.content|snippet:100|safe}} ...</p>
                                        </div>
                                    </div>
                                </div>
                            </div>
                            {%endfor%}


                            <div class="row">
                                <div class="col-lg-12">
                                    <div class="categories__pagination">

                                        {% if is_paginated %}
                                        <nav>
                                            <ul class="pagination">
                                                {% if page_obj.has_previous %}
                                                    <li>
                                                        <a href="?page={{ page_obj.previous_page_number }}">Previous</a>
                                                    </li>
                                                {% endif %}

                                            
                                                {% for num in page_obj.paginator.page_range %}
                                                    {% if page_obj.number == num %}
                                                        <li><a href="?page={{ num }}" class="page-link">{{ num }}</a></li>
                                                    {% else %}
                                                        <li>
                                                            <a href="?page={{ num }}" class="page-link">{{ num }}</a>
                                                        </li>
                                                    {% endif %}
                                                {% endfor %}
                                            

                                                {% if page_obj.has_next %}
                                                    <li>
                                                        <a href="?page={{ page_obj.next_page_number }}">Next</a>
                                                    </li>
                                                {% endif %}
                                            </ul>
                                        </nav>
                                        {% endif %}

                                        {% comment %} {% if posts.has_previous %}
                                            {% if s_flag %}
                                                <a href="?s={{s}}&page={{posts.previous_page_number}}">Previous</a>
                                            {% else %}
                                                <a href="?page={{posts.previous_page_number}}">Previous</a>
                                            {% endif %}
                                        {% endif %}

                                        {% for i in totalpages %}
                                            {% if posts.number == i %}
                                                {% if s_flag %}
                                                    <a href="?s={{s}}&page={{i}}" class="page-link">{{i}}</a>
                                                {% else %}
                                                    <a href="?page={{i}}" class="page-link">{{i}}</a>
                                                {% endif %}
                                            {% else %}
                                                {% if s_flag %}
                                                    <a href="?s={{s}}&page={{i}}" class="page-link">{{i}}</a>
                                                {% else %}
                                                    <a href="?page={{i}}" class="page-link">{{i}}</a>
                                                {% endif %}
                                            {% endif %}
                                        {% endfor %}

                                        {% if posts.has_next %}
                                            {% if s_flag %}
                                                <a href="?s={{s}}&page={{posts.next_page_number}}">Next</a>
                                            {% else %} 
                                                <a href="?page={{posts.next_page_number}}">Next</a>
                                            {% endif %}
                                        {% endif %} {% endcomment %}
                                        
                                    </div>
                                </div>
                            </div>
                        </div>

                        <div class="col-lg-4 col-md-4">
                            <div class="sidebar__item">
                                <div class="sidebar__subscribe__item">
									<form action="{% url "blog:search" %}" method="GET">
			                            <input placeholder="Search Posts" name="s" type="text" class="email-input">
			                            <button type="submit" class="site-btn">Search</button>
			                        </form>
                                </div>
                                <br><br>

                                {%include 'blog/blog_writer.html'%}

                                {% comment %} <div class="sidebar__follow__item">
                                    <div class="sidebar__item__title">
                                        <h6>Follow me</h6>
                                    </div>
                                    <div class="sidebar__item__follow__links">
                                        <a href="#"><i class="fa fa-facebook"></i></a>
                                        <a href="#"><i class="fa fa-twitter"></i></a>
                                        <a href="#"><i class="fa fa-youtube-play"></i></a>
                                        <a href="#"><i class="fa fa-instagram"></i></a>
                                        <a href="#"><i class="fa fa-envelope-o"></i></a>
                                    </div>
                                </div> {% endcomment %}

                                {% latestposts %}

                                <div class="sidebar__item__banner">
                                    <img src="{% static "template2/img/sidebar/banner.jpg" %}" alt="">
                                </div>

                                {% postcategories %}

                                <div class="sidebar__subscribe__item">
                                    <div class="sidebar__item__title">
                                        <h6>Subscribe</h6>
                                    </div>
                                    {% include 'website/website-subscribe.html' %}
                                </div>
                                
                                <br>
                                <div class="sidebar__item__categories">
                                    <div class="sidebar__item__title">
                                        <h6>Tag Clouds</h6>
                                    </div>
                                    {% tagclouds %}
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>
    <!-- Categories Section End -->

{%endblock%}

core/templates/blog/blog-single2.html
{%extends 'base2.html'%}
{%load static%}
{%load blog_tags%}
{% load humanize %}

    
{%block content%}

    <!-- Single Post Section Begin -->
    <section class="single-post spad">
        <div class="single-post__hero set-bg" {% if post.image %} data-setbg="{{ post.image.url }}" {% endif %}></div>
        <div class="container">
            <div class="row d-flex justify-content-center">
                <div class="col-lg-8">
                    <div class="single-post__title">
                        <div class="single-post__title__meta">
                            <h2>{{post.published_date|date:'d'}}</h2>
                            <span>{{post.published_date|date:'M'}}</span>
                        </div>
                        <div class="single-post__title__text">
                            <ul class="label">
                                {% for cat in post.category.all %}
                                <li href="{% url "blog:category" cat_name=cat.name %}">{{cat.name}} {%if not forloop.last%} {%endif%}</li>
                                {% endfor %}
                            </ul>
                            <h4>{{post.title}}</h4>
                            <ul class="widget">
                                <li>by {{post.author}}</li>
                                <li>{{post.counted_views}} views</li>
                                <li>{% comment_count post %} Comments</li>
                                <li>{{post.published_date|naturalday}}</li>
                            </ul>
                        </div>
                    </div>
                    <div class="single-post__social__item">
                        <ul>
                            <li><a href="#"><i class="fa fa-facebook"></i></a></li>
                            <li><a href="#"><i class="fa fa-twitter"></i></a></li>
                            <li><a href="#"><i class="fa fa-instagram"></i></a></li>
                            <li><a href="#"><i class="fa fa-youtube-play"></i></a></li>
                        </ul>
                    </div>
                    <div class="single-post__top__text">
                        <p>{{post.content|safe}} </p>
                    </div>
                    
                    
                    <div class="single-post__next__previous">
                        <div class="row">
                            <div class="col-lg-6 col-md-6 col-sm-6">
                                {% if pre == True %}
                                <a href="{% url "blog:blog_single" pid=post_pre.id %}" class="single-post__previous">
                                    <h6><span class="arrow_carrot-left"></span> Previous posts</h6>
                                    <div class="single-post__previous__meta">
                                        <h4>{{post_pre.published_date|date:'d'}}</h4>
                                        <span>{{post_pre.published_date|date:'M'}}</span>
                                    </div>
                                    <div class="single-post__previous__text">
                                        <span>{{post_pre.title}}</span>
                                        <h5>{{post_pre.author}}</h5>
                                    </div>
                                </a>
                                {% endif %}
                            </div>
                            <div class="col-lg-6 col-md-6 col-sm-6">
                                {% if after == True %}
                                <a href="{% url "blog:blog_single" pid=post_after.id %}" class="single-post__next">
                                    <h6>Next posts <span class="arrow_carrot-right"></span> </h6>
                                    <div class="single-post__next__meta">
                                        <h4>{{post_after.published_date|date:'d'}}</h4>
                                        <span>{{post_after.published_date|date:'M'}}</span>
                                    </div>
                                    <div class="single-post__next__text">
                                        <span>{{post_after.title}}</span>
                                        <h5>{{post_after.author}}</h5>
                                    </div>
                                </a>
                                {% endif %}
                            </div>
                        </div>
                    </div>

                    <div class="widget__title">
                        <h4>Tag Clouds</h4>
                    </div>
                    {% tagclouds %}

                    <div class="widget__title">
                        <h4>Post Categories</h4>
                    </div>
                    {% postcategories %}

                    <div class="single-post__author__profile">
                        <div class="single-post__author__profile__pic">
                            <img src="{% static "template2/img/categories/single-post/author-profile.jpg" %}" alt="">
                        </div>
                        <div class="single-post__author__profile__text">
                            <h4>Lena Mollein.</h4>
                            <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor
                                incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud
                                exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.</p>
                            <div class="single-post__author__profile__social">
                                <a href="#"><i class="fa fa-facebook"></i></a>
                                <a href="#"><i class="fa fa-twitter"></i></a>
                                <a href="#"><i class="fa fa-google-plus"></i></a>
                                <a href="#"><i class="fa fa-instagram"></i></a>
                                <a href="#"><i class="fa fa-youtube-play"></i></a>
                            </div>
                        </div>
                    </div>
             
                     {% latestcomments post %}                    
                   
                    
                    {% comment %} {% if comments %}
                    <div class="single-post__comment">
                        <div class="widget__title">
                            <h4>{{comments|length}} Comments</h4>
                        </div>
                        {% for comment in comments %}
                        <div class="single-post__comment__item">
                            <div class="single-post__comment__item__pic">
                                <img src="{% static "template2/img/categories/single-post/comment/comment-1.jpg" %}" alt="">
                            </div>
                            <div class="single-post__comment__item__text">
                                <h5>{{comment.subject}}</h5>
                                <span>{{comment.created_date|naturalday}}</span>
                                <p>{{comment.message}}</p>
                            </div>
                        </div>
                        {% endfor %}
                    </div>
                    {% endif %} {% endcomment %}

                    
                    {% comment %} <div class="single-post__leave__comment">
                        <div class="widget__title">
                            <h4>Leave a comment</h4>
                        </div>
                        <form action="{% url 'blog:blog_single' pid=post.id %}" method="POST">
                            {% csrf_token %}
                            <div class="input-list">
                            <input type='hidden' name='post' value={{post.id}}>
                            </div>
                            {% if request.user.is_authenticated %}
                                <div class="input-list">
                                    <input type="hidden" value={{request.user.username}} name="name" placeholder="Enter Name">
                                    <input type="hidden" value={{request.user.email}} name="email" placeholder="Enter email address">
                                </div>
                            {% else %}
                                <div class="input-list">
                                    <input type="text" name="name" placeholder="Enter Name" required>
                                    <input type="email" name="email" placeholder="Enter email address" required>
                                </div>
                            {% endif %}
                            <div class="input-list">
                            <input type="text" name="subject" placeholder="Subject" required>
                            <textarea name="message" placeholder="Message" required></textarea>
                            </div>
                            <button type="submit" class="site-btn">Submit</button>
                        </form>
                    </div> {% endcomment %}

                </div>
            </div>
        </div>
    </section>
    <!-- Single Post Section End -->

{%endblock%}

core/templates/blog/blog-tag-clouds.html
    <div class="single-post__tags">
        {% for tag in tags %}
        <span><a href="{% url 'blog:tag' tag_name=tag.name %}">{{tag.name}}</a></span>
        {% endfor %}
    </div>

core/templates/blog/blog_latestcomments.html
{%load static%}
{% load humanize %}


                    {% if comments %}
                    <div class="single-post__comment">
                        <div class="widget__title">
                            {% comment %} <a href="{% url "comment:task" pid=post.id %}" class="single-post__next"> {% endcomment %}
                            <h4>{{comment_count}} Total Comments</h4>
                        </div>
                        {% for comment in comments %}
                        <div class="single-post__comment__item">
                            <div class="single-post__comment__item__pic">
                                {% if comment.author.image %}<img src="{{ comment.author.image.url }}" alt="Profile Image" style="width:80px; height:80px; border-radius:50%;">{% endif %}
                                {% comment %} <img src="{% static "template2/img/categories/single-post/comment/comment-1.jpg" %}" alt=""> {% endcomment %}
                            </div> 
                            <div class="single-post__comment__item__text">
                                <h5>{{comment.title}}</h5>
                                <span>{{comment.created_date|naturalday}}</span>
                                <p>{{comment.author.first_name}}</p>
                            </div>
                        </div>
                        {% endfor %}
                    </div>
                    {% endif %}

                    <div class="single-post__leave__comment">
                        <div class="widget__title">
                            <a href="{% url "comment:task" pid=post.id %}" class="single-post__next">
                            <h4>Read more and Leave a comment</h4>
                        </div>
                    </div>

core/templates/blog/blog_postcategories.html
<div class="sidebar__item__categories">
    <div class="sidebar__item__title">
        <h6>Categories</h6>
    </div>
    <ul>
        {% for name,count in categories.items %}
        <li><a href="{% url "blog:category" cat_name=name %}">{{name}} <span>{{count}}</span></a></li>
        {% endfor %}
    </ul>
</div>